saving_path: './data'
iris:
  host: 'rtserve.iris.washington.edu'
  port: 18000
  channels:
    - 'YN/SGBS2'
    - 'XL/MG04'
    - 'WY/YGC'
geofon:
  host: 'geofon-open.gfz-potsdam.de'
  port: 18000
  channels:
    - 'GE/SFJD'
    - 'GE/PUL'
    - 'GE/KBU'
ipgp:
  url: 'http://ws.ipgp.fr/fdsnws'
  channels:
    - 'G/CCD'
    - 'PF/CAS'